#!/usr/bin/env bash

WALNUT_PATH="$HOME/Walnut"
WALNUT_WORD_PATH="$WALNUT_PATH/Word Automata Library"
WALNUT_AUTOMATA_PATH="$WALNUT_PATH/Automata Library"
WALNUT_COMMAND_FILES_PATH="$WALNUT_PATH/Command Files"
WALNUT_CUSTOM_BASES_PATH="$WALNUT_PATH/Custom Bases"
WALNUT_RESULTS_PATH="$WALNUT_PATH/Result"
GENERAL_ADDITION_AUTOMATON_PATH="./general-ostrowski-addition-automaton-java"
RESULTS="results"

